/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.vocidelcodice.orders_and_registrations;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class OrderCommandHandlerTest {
    @Mock
    private OrderRepository orderRepository;

    @Test void create_an_order() {
        OrderCommandHandler orderCommandHandler = new OrderCommandHandler(orderRepository);
        orderCommandHandler.handle(new RegisterToConferenceCommand());

        Order order = new Order();
        verify(orderRepository).save(order);
    }
}
